import { useMemo, useState, type ReactNode } from 'react';

import { formatINR } from '@fincalc/ui';
import { emi, type AgeBand, type TaxRegime } from '@fincalc/engine';

import { Amount } from '../../components/Amount';
import { Callout, CalcShell, NumberField, SelectField, SubmitButton } from '../../components/CalcShell';
import { NetWorthTrajectoryChart } from '../../components/charts';
import {
  buildLayerOneComparison,
  buildAnnualNetWorthTrajectory,
  estimateMonthlyRentFromPrice,
  DEFAULT_DOWN_PAYMENT_PERCENT,
  DEFAULT_HOME_LOAN_RATE_PERCENT,
  DEFAULT_HOME_LOAN_TENURE_YEARS,
  DEFAULT_HOUSEHOLD_AGE,
  DEFAULT_HOUSEHOLD_REGIME,
  DEFAULT_MAINTENANCE_PERCENT_OF_PRICE,
  DEFAULT_PROPERTY_APPRECIATION_PERCENT,
  DEFAULT_PROPERTY_TAX_PERCENT_OF_PRICE,
  DEFAULT_REINVESTMENT_RATE_PERCENT,
  DEFAULT_RENTAL_YIELD_PERCENT,
  DEFAULT_SECURITY_DEPOSIT_MONTHS,
  type AnnualNetWorthPoint,
  type LayerOneResult,
} from '../../lib/scenario-builder';

/**
 * Door 2 ("Should I rent or buy?") and Tier 1's "Rent vs Buy" module
 * (brief §3, §4) are the same underlying question with the same required
 * output — full opportunity-cost treatment of the down payment, and a
 * break-even year — so both route here rather than duplicating the
 * Allocation Comparator's Buy-vs-Rent-and-invest mechanism a second time.
 * `buildLayerOneComparison` already computes all four horizons (5/10/15/25
 * years) in one call; the results table below reads straight off that.
 *
 * Phase 9.1: desktop layout and real charts (see CalcShell.tsx and
 * charts.tsx module doc comments).
 *
 * Phase 9.2 (user feedback: "other than Household income... Monthly
 * housing budget, everything else is a blackbox for the user... the user
 * should be able to engage all the available levers to move the various
 * metrics."): every documented default in scenario-builder.ts became a
 * field here too, pre-filled with that same DEFAULT_* constant and fully
 * editable.
 *
 * Phase 9.3, two follow-up pieces of feedback on that form:
 *
 * (1) "there's no provision to set the 2 key things. base price of the
 * purchased flat... & monthly rents - those are autogenerated. the user
 * should be able to control them." The sized home price and assumed rent
 * were still silent outputs, not inputs. Fixed with `OverridableNumberField`
 * below: it shows the live auto-computed figure (via
 * `estimateHomeSizingFromBudget`/`estimateMonthlyRentFromPrice`, the exact
 * arithmetic `buildLayerOneComparison` itself uses) until the user types
 * their own number, at which point it "sticks" — further changes to the
 * budget or loan terms stop moving it — and a "Reset to auto" link puts it
 * back in sync.
 *
 * (2) "the list of levers has grown too long. you need to group them
 * thoughtfully & arrange them across the screen in a way that minimizes
 * scroll, both for desktop & mobiles." The Layer-2 levers are grouped
 * into `<LeverGroup>` disclosures by what they affect rather than the
 * order they happened to be added in, each laying its fields out two per
 * row from `sm:` up. `<details>` is used deliberately over a React-state
 * accordion — free scroll-reduction with zero extra JS state,
 * keyboard-accessible by default, consistent with this project's "no
 * framework where the platform already does the job" bias (router.ts's
 * hash routing).
 *
 * Phase 9.4, two more pieces of feedback looking at the Phase 9.3 page:
 *
 * (1) "every other lever sets the 'as-is' state. the annual appreciation
 * & returns on surplus are the main levers for simulating scenarios.
 * bring these to the top above the graph & provide sliders." Property
 * appreciation and reinvestment return are pulled out of the "Growth &
 * reinvestment" lever group entirely (that group is gone — it only ever
 * held these two) and now live as `SliderLever` controls in the results
 * section, directly above the chart. Every other lever still configures
 * the household's actual, as-is situation in the collapsible groups below
 * the submit button; these two are the "what if" dials for exploring the
 * decision once a baseline exists. No new wiring was needed for the
 * live-recompute — `outcome`'s memo already depended on
 * `propertyAppreciationPercent`/`reinvestmentRatePercent`, since every
 * lever has recomputed reactively since Phase 9.2; only *where* the
 * control renders changed.
 *
 * (2) "in the graph, instead of bars, ... line charts would be better
 * representations, showing the year on year change, as well as the
 * possible cutovers." `buildAnnualNetWorthTrajectory` (scenario-builder.ts)
 * re-runs the same Buy/Rent comparison at one horizon per year instead of
 * the four canonical buckets, and `NetWorthTrajectoryChart` (charts.tsx)
 * plots both scenarios as continuous lines with a reference line at every
 * year the two actually cross — not just the nearest of 5/10/15/25.
 * `computeBreakEven` below now scans this same year-by-year trajectory,
 * so the headline sentence is exact ("year 7", not "year 10 or earlier")
 * without changing its underlying meaning (still the first year Buy's
 * terminal net worth is at least Rent's). The four-horizon results table,
 * the hurdle-rate sentence, the assumptions panel, Monte Carlo and CSV
 * export are all untouched — they read `layerOne.result` directly, which
 * `buildLayerOneComparison` still computes at exactly the same four
 * horizons it always has.
 *
 * Phase 9.5, immediate follow-up feedback on the Phase 9.4 slider panel:
 * the three numbers that actually explain "what am I comparing" — the
 * Buy scenario's EMI, the Rent scenario's equivalent rent, and the monthly
 * surplus renting would free up to invest — were only ever buried in the
 * assumptions-used panel at the bottom (EMI wasn't even shown there at
 * all). A three-tile stat row now sits directly below the slider panel,
 * above the chart, computed straight from `layerOne.buy`/`layerOne.rent`
 * (`emi()`, the same engine primitive every loan Position is built on, is
 * the only new call — no new engine plumbing) plus the household's own
 * maintenance lever, so it's correct even when the home price is entered
 * directly (Phase 9.3) rather than budget-derived. Deliberately EMI +
 * maintenance only, not the once-a-year property tax lump sum — folding
 * an annual charge into a monthly figure would misrepresent it as a
 * recurring cost, which it isn't (see `real-estate.ts`'s `buildCoreRows`:
 * property tax posts once every 12th month, never spread monthly).
 *
 * Phase 9.6 (immediate follow-up: "lets simplify the workings. Remove the
 * city, remove the Monthly housing budget. surplus now = emi - rent"):
 * two fields come off this form entirely. The City selector already only
 * ever showed one, disabled option (Hyderabad is still the only city
 * @fincalc/data ships stamp-duty rates for), so it was pure clutter — the
 * value is now just hard-coded in the `buildLayerOneComparison` call
 * below. "Monthly housing budget" was more than clutter: it silently
 * decided three things at once (the sized home price, and the maintenance
 * and property-tax allowances), which is exactly the "blackbox" feel
 * Phase 9.2 was trying to get away from. "Base flat price" now takes its
 * place as a plain, always-required direct input (no more Auto/override
 * toggle — `estimateHomeSizingFromBudget` and the auto-sizing preview are
 * gone from this page); maintenance and property tax move from "% of
 * budget" to "% of price, annual" accordingly (see
 * `DEFAULT_MAINTENANCE_PERCENT_OF_PRICE`/`DEFAULT_PROPERTY_TAX_PERCENT_OF_PRICE`
 * and the Phase 9.6 branch in scenario-builder.ts's
 * `buildLayerOneComparison` — purely additive there, so the flagship
 * Allocation Comparator's own budget-driven flow is untouched). The stat
 * row's surplus formula simplifies to exactly `EMI − rent`, dropping the
 * maintenance term.
 *
 * Phase 9.7 (immediate follow-up: "what does the graph exactly show?
 * mention that somewhere clearly" + a "Home purchase & loan" layout
 * request): a one-line caption now sits directly above the trajectory
 * chart explaining what it plots and what the dashed reference lines
 * mean, rather than leaving that to the axis labels and legend alone.
 * Separately, the "Home purchase & loan" box's four fields no longer sit
 * in the generic two-per-row `LeverGroup` grid every other box uses —
 * this one box gets a two-column split with a vertical divider: Base
 * flat price plus a new, previously-buried `Loan amount` readout on the
 * left (the loan amount was only ever visible parenthetically in the
 * bottom assumptions panel before this), Down payment/loan rate/tenure
 * stacked on the right.
 *
 * Phase 9.8 (immediate follow-up, looking at a specific year-1 figure on
 * the chart: "how does the net worth become [X] in year 1? what's the
 * calculation behind this? include this on the caption as well"): the
 * Phase 9.7 caption above the chart now spells out the per-scenario
 * arithmetic, not just what the chart plots. Both scenarios' terminal net
 * worth are `ownPositionsValueAfterTax + sweepValueAfterTax` from the
 * engine's own comparator.ts (see that file's `projectScenarioGivenTarget`)
 * as of the exit month closing that year — i.e. "if you exited today,
 * after tax." For Buy, `ownPositionsValueAfterTax` is the home's
 * appreciated value minus the remaining loan balance minus stamp-duty/
 * exit-cost/capital-gains tax on that notional sale; `sweepValueAfterTax`
 * is 0 in year 1 for the page's defaults (Buy's own monthly cost already
 * sets the equalised target every month, so it has no surplus left to
 * sweep). For Rent, `ownPositionsValueAfterTax` is just the refundable
 * security deposit; `sweepValueAfterTax` is the invested EMI-vs-rent
 * gap — a large month-1 lump (target minus rent, which nets out to
 * roughly the down payment plus entry costs) plus a smaller gap every
 * month after, compounded at the reinvestment rate and taxed on exit.
 * This is why Rent usually leads early: its lump-sum month-1 investment
 * has a year to compound while Buy is still absorbing entry costs and a
 * same-year "sale" is taxed at the least favourable (short-term) rate —
 * nobody's meant to actually sell in year 1, this is a same-day
 * mark-to-market snapshot so every year compares on equal footing.
 */
interface BreakEven {
  crosses: boolean;
  year: number;
  buyNW: number;
  rentNW: number;
}

const REGIME_OPTIONS: { value: TaxRegime; label: string }[] = [
  { value: 'new', label: 'New regime' },
  { value: 'old', label: 'Old regime' },
];
const AGE_OPTIONS: { value: AgeBand; label: string }[] = [
  { value: 'under60', label: 'Under 60' },
  { value: '60to79', label: '60–79 (senior citizen)' },
  { value: '80plus', label: '80+ (super senior)' },
];

/** The first year (if any, within the trajectory) Buy's net worth is at least Rent's — see the module doc comment, Phase 9.4 point (2). */
function computeBreakEven(trajectory: readonly AnnualNetWorthPoint[]): BreakEven | null {
  if (trajectory.length === 0) return null;
  const crossIndex = trajectory.findIndex((p) => p.buyNetWorth >= p.rentNetWorth);
  const idx = crossIndex === -1 ? trajectory.length - 1 : crossIndex;
  const point = trajectory[idx]!;
  return { crosses: crossIndex !== -1, year: point.year, buyNW: point.buyNetWorth, rentNW: point.rentNetWorth };
}

/** Every year the two scenarios' net worth actually changes lead — a sign flip in (buy − rent) — for the chart's reference lines. Distinct from `computeBreakEven`, which only reports the first. */
function computeCrossoverYears(trajectory: readonly AnnualNetWorthPoint[]): number[] {
  const years: number[] = [];
  for (let i = 1; i < trajectory.length; i++) {
    const prevDiff = trajectory[i - 1]!.buyNetWorth - trajectory[i - 1]!.rentNetWorth;
    const currDiff = trajectory[i]!.buyNetWorth - trajectory[i]!.rentNetWorth;
    if (prevDiff !== 0 && Math.sign(prevDiff) !== Math.sign(currDiff)) {
      years.push(trajectory[i]!.year);
    }
  }
  return years;
}

/** A collapsible group of levers (Phase 9.3) — see the module doc comment for why `<details>` over a state-driven accordion. Fields lay out two-per-row from `sm:` up, one-per-row below it, so a narrow phone never gets a cramped input. */
function LeverGroup({ title, defaultOpen = false, children }: { title: string; defaultOpen?: boolean; children: ReactNode }) {
  return (
    <details open={defaultOpen} className="rounded-sm border border-hairline">
      <summary className="cursor-pointer select-none px-3 py-2.5 text-sm text-ink">{title}</summary>
      <div className="grid grid-cols-1 gap-x-3 gap-y-4 border-t border-hairline p-3 sm:grid-cols-2">{children}</div>
    </details>
  );
}

/**
 * A NumberField that can be either "auto" (showing a live-computed value
 * driven by other fields) or "overridden" (showing exactly what the user
 * typed, and no longer moving when those other fields change) — see the
 * module doc comment, Phase 9.3 point (1). `isOverridden` alone decides
 * which state the badge/reset-link shows; the caller is responsible for
 * passing the right `value` for each state (auto-computed or the stored
 * override).
 */
function OverridableNumberField({
  label,
  hint,
  value,
  isOverridden,
  onChange,
  onReset,
  min = 0,
  max,
  step = 1,
}: {
  label: string;
  hint?: string;
  value: number;
  isOverridden: boolean;
  onChange: (v: number) => void;
  onReset: () => void;
  min?: number;
  max?: number;
  step?: number;
}) {
  return (
    <label className="flex flex-col gap-1.5 text-sm">
      <span className="flex items-baseline justify-between gap-2">
        <span className="text-ink">{label}</span>
        {isOverridden ? (
          <button type="button" onClick={onReset} className="shrink-0 text-xs text-rust hover:underline">
            Reset to auto
          </button>
        ) : (
          <span className="shrink-0 text-xs text-ink-muted">Auto</span>
        )}
      </span>
      <input
        type="number"
        inputMode="decimal"
        min={min}
        max={max}
        step={step}
        required
        value={Number.isFinite(value) ? value : ''}
        onChange={(e) => onChange(e.target.value === '' ? NaN : Number(e.target.value))}
        className="rounded-sm border border-hairline bg-paper px-3 py-2 font-mono tabular-nums text-ink"
      />
      {hint && <span className="text-xs text-ink-muted">{hint}</span>}
    </label>
  );
}

/**
 * Phase 9.4: a labelled range slider for the two assumptions that most
 * directly drive "what if" scenario exploration — see the module doc
 * comment, point (1). Every other lever lives in the collapsible groups
 * below the submit button and sets the household's as-is baseline; these
 * two live above the chart instead, because changing them is the point —
 * dragging either one re-simulates immediately via the same live-recompute
 * wiring every lever has had since Phase 9.2.
 */
function SliderLever({
  label,
  hint,
  value,
  onChange,
  min,
  max,
  step,
  format,
}: {
  label: string;
  hint?: string;
  value: number;
  onChange: (v: number) => void;
  min: number;
  max: number;
  step: number;
  format: (v: number) => string;
}) {
  return (
    <label className="flex flex-col gap-1.5 text-sm">
      <span className="flex items-baseline justify-between gap-2">
        <span className="text-ink">{label}</span>
        <span className="font-mono tabular-nums text-rust">{format(value)}</span>
      </span>
      <input
        type="range"
        min={min}
        max={max}
        step={step}
        value={value}
        onChange={(e) => onChange(Number(e.target.value))}
        className="w-full accent-rust"
      />
      {hint && <span className="text-xs text-ink-muted">{hint}</span>}
    </label>
  );
}

export function RentVsBuy() {
  const [monthlyIncome, setMonthlyIncome] = useState(450_000);
  const [homePrice, setHomePrice] = useState(22_000_000);
  const [homeLoanRatePercent, setHomeLoanRatePercent] = useState(DEFAULT_HOME_LOAN_RATE_PERCENT);
  const [homeLoanTenureYears, setHomeLoanTenureYears] = useState(DEFAULT_HOME_LOAN_TENURE_YEARS);
  const [downPaymentPercent, setDownPaymentPercent] = useState(DEFAULT_DOWN_PAYMENT_PERCENT);
  const [propertyAppreciationPercent, setPropertyAppreciationPercent] = useState(DEFAULT_PROPERTY_APPRECIATION_PERCENT);
  const [reinvestmentRatePercent, setReinvestmentRatePercent] = useState(DEFAULT_REINVESTMENT_RATE_PERCENT);
  const [rentalYieldPercent, setRentalYieldPercent] = useState(DEFAULT_RENTAL_YIELD_PERCENT);
  const [maintenancePercentOfPrice, setMaintenancePercentOfPrice] = useState(DEFAULT_MAINTENANCE_PERCENT_OF_PRICE);
  const [propertyTaxPercentOfPrice, setPropertyTaxPercentOfPrice] = useState(DEFAULT_PROPERTY_TAX_PERCENT_OF_PRICE);
  const [securityDepositMonths, setSecurityDepositMonths] = useState(DEFAULT_SECURITY_DEPOSIT_MONTHS);
  const [householdRegime, setHouseholdRegime] = useState<TaxRegime>(DEFAULT_HOUSEHOLD_REGIME);
  const [householdAge, setHouseholdAge] = useState<AgeBand>(DEFAULT_HOUSEHOLD_AGE);
  // Phase 9.3 (rent only, since Phase 9.6): undefined = "still auto-computed"; a number = "user overrode it".
  const [monthlyRentOverride, setMonthlyRentOverride] = useState<number | undefined>(undefined);
  const [submitted, setSubmitted] = useState(false);

  // Live preview of the auto-sized rent — the same formula
  // buildLayerOneComparison itself calls — so "Assumed monthly rent"
  // tracks the flat price and yield even before the form's first submit,
  // and snaps back to tracking them the moment the override is reset.
  // (Phase 9.6: the flat price itself is no longer auto-sized — it's a
  // plain required input now, so there's no equivalent preview for it.)
  const autoMonthlyRent = useMemo(
    () => estimateMonthlyRentFromPrice(homePrice, rentalYieldPercent),
    [homePrice, rentalYieldPercent],
  );
  const displayedMonthlyRent = monthlyRentOverride ?? autoMonthlyRent;

  // Phase 9.7: a simple derived readout for the "Home purchase & loan" box
  // — previously only visible parenthetically in the bottom assumptions
  // panel ("(₹X loan)"). Cheap arithmetic, no memo needed.
  const loanAmount = homePrice * (1 - downPaymentPercent / 100);

  const outcome = useMemo<{ ok: true; value: LayerOneResult } | { ok: false; error: string } | null>(() => {
    if (!submitted) return null;
    try {
      const value = buildLayerOneComparison({
        // Phase 9.6: City is hard-coded — Hyderabad is still the only city
        // @fincalc/data ships stamp-duty rates for (see the module doc
        // comment); homePriceOverride is always supplied now, so the
        // budget-derived sizing branch never runs on this page.
        city: 'hyderabad',
        monthlyHouseholdIncomeNet: monthlyIncome,
        homePriceOverride: homePrice,
        horizonYears: 25,
        homeLoanRatePercent,
        homeLoanTenureYears,
        downPaymentPercent,
        propertyAppreciationPercent,
        reinvestmentRatePercent,
        rentalYieldPercent,
        maintenancePercentOfPrice,
        propertyTaxPercentOfPrice,
        securityDepositMonths,
        householdRegime,
        householdAge,
        ...(monthlyRentOverride !== undefined ? { monthlyRentOverride } : {}),
      });
      return { ok: true, value };
    } catch (e) {
      const message = e instanceof Error ? e.message : "Something about these numbers didn't compute. Try different values.";
      return { ok: false, error: message };
    }
  }, [
    submitted,
    monthlyIncome,
    homePrice,
    homeLoanRatePercent,
    homeLoanTenureYears,
    downPaymentPercent,
    propertyAppreciationPercent,
    reinvestmentRatePercent,
    rentalYieldPercent,
    maintenancePercentOfPrice,
    propertyTaxPercentOfPrice,
    securityDepositMonths,
    householdRegime,
    householdAge,
    monthlyRentOverride,
  ]);

  const layerOne = outcome?.ok ? outcome.value : null;
  const error = outcome && !outcome.ok ? outcome.error : null;

  // Phase 9.4: the year-by-year trajectory the line chart and the exact
  // break-even year both read from — a genuine second `compare()` call
  // (see the module doc comment), so this one is worth memoizing.
  const trajectory = useMemo<AnnualNetWorthPoint[]>(
    () => (layerOne ? buildAnnualNetWorthTrajectory(layerOne) : []),
    [layerOne],
  );

  // Deliberately not useMemo: cheap linear scans over a ~25-element array
  // — a second memo here isn't worth it, and the equivalent for-loop
  // version tripped the React Compiler's manual-memoization-preservation
  // check when this was last tried (Phase 9.3).
  const breakEven = computeBreakEven(trajectory);
  const crossoverYears = computeCrossoverYears(trajectory);

  // Phase 9.5: the three headline monthly figures for the stat row above
  // the chart — see the module doc comment. Cheap, so computed directly
  // like breakEven/crossoverYears above rather than memoized. Phase 9.6
  // simplified the surplus formula to plain EMI minus rent.
  const monthlyEmi = layerOne ? emi(layerOne.buy.loanPrincipal, layerOne.buy.loanRatePercent / 100, layerOne.buy.tenureYears * 12) : 0;
  const surplusIfRenting = layerOne ? monthlyEmi - layerOne.rent.assumedMonthlyRent : 0;

  return (
    <CalcShell
      title="Should I rent or buy?"
      subtitle="Buying a home your budget can support, versus renting an equivalent home and investing the difference — on equal monthly outflow, after tax, including the opportunity cost of the down payment."
      back="home"
      backLabel="← FinCalc"
      form={
        <form
          className="flex flex-col gap-5"
          onSubmit={(e) => {
            e.preventDefault();
            setSubmitted(true);
          }}
        >
          <NumberField label="Household income, per month (take-home)" value={monthlyIncome} onChange={setMonthlyIncome} />

          <p className="text-xs text-ink-muted">
            Every assumption below is editable, grouped by what it affects, and sets your as-is baseline. Open a
            section to see or change its levers. Property appreciation and reinvestment return — the two "what if"
            dials for exploring the decision — moved above the chart once you compare.
          </p>

          <LeverGroup title="Home purchase & loan" defaultOpen>
            <div className="flex flex-col gap-4 sm:col-span-2 sm:flex-row sm:divide-x sm:divide-hairline">
              <div className="flex flex-col gap-4 sm:w-1/2 sm:pr-4">
                <NumberField
                  label="Base flat price (excl. stamp duty)"
                  hint="The purchase price you're comparing against — everything else in this section sizes the loan and the ongoing costs off it."
                  value={homePrice}
                  onChange={setHomePrice}
                  step={1}
                />
                <div className="flex flex-col gap-1 text-sm">
                  <span className="text-xs text-ink-muted">Loan amount</span>
                  <Amount value={loanAmount} className="text-base text-ink" />
                  <span className="text-xs text-ink-muted">Flat price minus down payment.</span>
                </div>
              </div>
              <div className="flex flex-col gap-4 sm:w-1/2 sm:pl-4">
                <NumberField label="Down payment (%)" value={downPaymentPercent} onChange={setDownPaymentPercent} min={5} max={90} step={1} />
                <NumberField label="Loan interest rate, annual (%)" value={homeLoanRatePercent} onChange={setHomeLoanRatePercent} min={0} max={20} step={0.1} />
                <NumberField label="Loan tenure (years)" value={homeLoanTenureYears} onChange={setHomeLoanTenureYears} min={1} max={30} step={1} />
              </div>
            </div>
          </LeverGroup>

          <LeverGroup title="Rent scenario" defaultOpen>
            <OverridableNumberField
              label="Assumed monthly rent"
              hint="Auto-sized from the flat price × rental yield unless you enter your own."
              value={displayedMonthlyRent}
              isOverridden={monthlyRentOverride !== undefined}
              onChange={setMonthlyRentOverride}
              onReset={() => setMonthlyRentOverride(undefined)}
              step={1}
            />
            <NumberField
              label="Rental yield (%)"
              value={rentalYieldPercent}
              onChange={setRentalYieldPercent}
              min={0.5}
              max={10}
              step={0.1}
              hint="Ignored once you enter a rent above."
            />
            <NumberField label="Security deposit (months' rent)" value={securityDepositMonths} onChange={setSecurityDepositMonths} min={0} max={12} step={1} />
          </LeverGroup>

          <LeverGroup title="Ongoing costs">
            <NumberField
              label="Maintenance (% of price, annual)"
              value={maintenancePercentOfPrice}
              onChange={setMaintenancePercentOfPrice}
              min={0}
              max={3}
              step={0.05}
            />
            <NumberField
              label="Property tax (% of price, annual)"
              value={propertyTaxPercentOfPrice}
              onChange={setPropertyTaxPercentOfPrice}
              min={0}
              max={2}
              step={0.05}
            />
          </LeverGroup>

          <LeverGroup title="Household tax">
            <SelectField label="Tax regime" value={householdRegime} onChange={setHouseholdRegime} options={REGIME_OPTIONS} />
            <SelectField label="Age" value={householdAge} onChange={setHouseholdAge} options={AGE_OPTIONS} />
          </LeverGroup>

          <SubmitButton>Compare →</SubmitButton>
        </form>
      }
    >
      {error && <Callout>{error}</Callout>}

      {layerOne && breakEven && (
        <section className="flex flex-col gap-8" aria-label="Rent vs buy result">
          <p className="font-serif-heading max-w-md text-2xl leading-snug text-ink sm:text-3xl">
            {breakEven.crosses ? (
              <>
                Buying pulls ahead of renting-and-investing by <span className="text-rust">year {breakEven.year}</span>.
              </>
            ) : (
              <>
                Renting-and-investing stays ahead of buying through year {breakEven.year}, the longest horizon we project.
              </>
            )}
          </p>

          <div className="rounded-sm border border-hairline p-4">
            <p className="mb-3 text-sm text-ink">
              Simulate: the two assumptions that move this decision most. Every other lever in the form sets the
              as-is baseline — these two are for exploring "what if."
            </p>
            <div className="grid grid-cols-1 gap-x-6 gap-y-5 sm:grid-cols-2">
              <SliderLever
                label="Property appreciation, annual"
                value={propertyAppreciationPercent}
                onChange={setPropertyAppreciationPercent}
                min={0}
                max={20}
                step={0.1}
                format={(v) => `${v.toFixed(1)}%`}
              />
              <SliderLever
                label="Return on invested surplus, annual"
                value={reinvestmentRatePercent}
                onChange={setReinvestmentRatePercent}
                min={0}
                max={25}
                step={0.1}
                format={(v) => `${v.toFixed(1)}%`}
                hint="What both scenarios' surplus compounds at."
              />
            </div>
          </div>

          <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
            <div className="rounded-sm border border-hairline p-4">
              <p className="text-xs text-ink-muted">Monthly EMI</p>
              <Amount value={monthlyEmi} compact={false} className="font-serif-heading text-2xl text-ink" />
            </div>
            <div className="rounded-sm border border-hairline p-4">
              <p className="text-xs text-ink-muted">Equivalent rent</p>
              <Amount value={layerOne.rent.assumedMonthlyRent} compact={false} className="font-serif-heading text-2xl text-ink" />
            </div>
            <div className="rounded-sm border border-hairline p-4">
              <p className="text-xs text-ink-muted">Surplus invested, if renting</p>
              <Amount value={surplusIfRenting} compact={false} className="font-serif-heading text-2xl text-rust" />
              <p className="mt-1 text-xs text-ink-muted">EMI minus rent — swept into the shared investment each month.</p>
            </div>
          </div>

          <div className="flex flex-col gap-2">
            <p className="text-sm text-ink">
              Net worth by year — what each path would leave you with if you exited that year. For Buy: today's home
              value after appreciation, minus what's still owed on the loan, minus the tax and costs of selling. For
              Rent: the down payment plus every month's EMI-vs-rent gap, invested and grown, minus tax on cashing
              out. Early years favour Rent because that gap starts as one big lump (roughly the down payment plus
              stamp duty) invested from month one, while Buy is still carrying entry costs and a short-term sale
              would be taxed hardest. Dashed lines mark the years the lead changes.
            </p>
            <NetWorthTrajectoryChart
              data={trajectory.map((p) => ({
                year: p.year,
                [layerOne.scenarios[0].name]: p.buyNetWorth,
                [layerOne.scenarios[1].name]: p.rentNetWorth,
              }))}
              seriesAKey={layerOne.scenarios[0].name}
              seriesAName={layerOne.scenarios[0].name}
              seriesBKey={layerOne.scenarios[1].name}
              seriesBName={layerOne.scenarios[1].name}
              crossoverYears={crossoverYears}
              ariaLabel={`Net worth by year, ${layerOne.scenarios[0].name} versus ${layerOne.scenarios[1].name}`}
            />
          </div>

          <div className="overflow-x-auto">
            <table className="w-full min-w-[320px] border-collapse text-sm">
              <thead>
                <tr className="border-b border-hairline text-left text-ink-muted">
                  <th className="py-2 pr-3 font-normal">Horizon</th>
                  <th className="py-2 pr-3 font-normal">Buy</th>
                  <th className="py-2 pr-3 font-normal">Rent &amp; invest</th>
                </tr>
              </thead>
              <tbody>
                {[5, 10, 15, 25].map((y, i) => {
                  const [buyComparison, rentComparison] = layerOne.result.scenarios;
                  return (
                    <tr key={y} className="border-b border-hairline/60">
                      <td className="py-2 pr-3 align-top text-ink-muted">{y}yr</td>
                      <td className="py-2 pr-3 align-top"><Amount value={buyComparison!.perHorizon[i]!.terminalNetWorth} className="text-ink" /></td>
                      <td className="py-2 pr-3 align-top"><Amount value={rentComparison!.perHorizon[i]!.terminalNetWorth} className="text-ink" /></td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>

          {layerOne.result.parityWarnings.length > 0 && (
            <ul className="flex flex-col gap-2">
              {layerOne.result.parityWarnings.map((w, i) => (
                <li key={i} className="rounded-sm border border-ochre bg-ochre/10 px-4 py-3 text-sm text-ink">⚠ {w.message}</li>
              ))}
            </ul>
          )}

          <div className="rounded-sm border border-hairline px-4 py-4 text-sm text-ink-muted">
            <p className="mb-2 text-ink">Assumptions used</p>
            <ul className="flex flex-col gap-1">
              {layerOne.assumptions.map((a) => (
                <li key={a.id}>{a.label}: <span className="font-mono tabular-nums text-ink">{(a.rate * 100).toFixed(1)}%</span></li>
              ))}
              <li>
                Home price: <Amount value={layerOne.buy.propertyPrice} className="text-ink" /> ({formatINR(layerOne.buy.loanPrincipal, { compact: true })} loan)
              </li>
              <li>
                Home loan: <span className="font-mono tabular-nums text-ink">{layerOne.buy.loanRatePercent.toFixed(1)}%</span> for{' '}
                <span className="font-mono tabular-nums text-ink">{layerOne.buy.tenureYears}yr</span>,{' '}
                <span className="font-mono tabular-nums text-ink">{layerOne.buy.downPaymentPercent.toFixed(0)}%</span> down
              </li>
              <li>
                Assumed rent: <Amount value={layerOne.rent.assumedMonthlyRent} className="text-ink" />/month
                <span className="text-ink-muted">{monthlyRentOverride !== undefined ? ' — entered directly' : ' — auto-sized from flat price × yield'}</span>
              </li>
              <li>
                Rental yield: <span className="font-mono tabular-nums text-ink">{layerOne.rent.rentalYieldPercent.toFixed(1)}%</span>, security deposit{' '}
                <span className="font-mono tabular-nums text-ink">{layerOne.rent.securityDepositMonths}</span> months
              </li>
              <li>
                Tax regime: <span className="text-ink">{layerOne.household.regime === 'new' ? 'New' : 'Old'}</span>, age{' '}
                <span className="text-ink">
                  {layerOne.household.age === 'under60' ? 'under 60' : layerOne.household.age === '60to79' ? '60–79' : '80+'}
                </span>
              </li>
            </ul>
          </div>
        </section>
      )}
    </CalcShell>
  );
}
