/**
 * Layer 1 of the Allocation Comparator (brief §4): turns the four inputs
 * the brief specifies — city, household income, monthly housing budget,
 * horizon — into a real two-scenario comparison run through the actual
 * Phase 3/4 engine, with every default assumption a named, documented
 * constant below rather than a magic number buried in the math.
 *
 * The two scenarios are deliberately the simplest honest pair that
 * showcases what makes this engine different from a naive calculator:
 *
 *   Buy        — a home sized so its EMI (plus a maintenance/property-tax
 *                allowance) fits the stated budget, self-occupied.
 *   Rent & invest — rent an equivalent home at an assumed market yield;
 *                the Comparator's own equal-outflow sweep (principle 1 &
 *                10) invests whatever the budget doesn't go to rent — this
 *                *is* "rent and invest the difference", computed by the
 *                same mechanism the founding scenario uses, not a
 *                hand-rolled SIP bolted on separately.
 *
 * Both scenarios share one sweep instrument at one rate (principle 9) —
 * the exact asymmetry the brief's §1A canonical failure case (13.5% vs 6%)
 * warns against never gets a chance to creep in here.
 *
 * City is fixed to Hyderabad for now: it's the only city
 * @fincalc/data ships real stamp-duty rates for (see
 * claude/decisions-and-workflow.md, "Maharashtra municipal_corporation
 * ... deliberately unshipped"). Guessing a rate for an unlisted city would
 * break the project's own "flag rather than guess" rule, so the field is
 * real but single-valued until more cities' data ships.
 *
 * Phase 9.2 (user feedback on the live Rent vs Buy page: "everything else
 * is a blackbox for the user... the user should be able to engage all the
 * available levers"): every documented default constant below is now an
 * *optional override* on LayerOneInputs rather than a hard-coded value —
 * RentVsBuy.tsx renders one editable field per lever, pre-filled with
 * these same DEFAULT_* constants (imported, not re-typed, so the form and
 * the engine can never silently drift apart). Omit a field (or reuse an
 * old saved/shared link from before this phase) and the named default
 * still applies — this is why every new field on LayerOneInputs is
 * optional rather than a breaking signature change.
 *
 * Phase 9.3 (user feedback, looking at the Phase 9.2 form: "there's no
 * provision to set the 2 key things. base price of the purchased flat
 * (excl. registration, stamp charges) & monthly rents - those are
 * autogenerated. the user should be able to control them"): the two
 * numbers Phase 9.2 still derived silently — the Buy scenario's sized
 * home price and the Rent scenario's assumed rent — are now direct
 * optional overrides too (`homePriceOverride`/`monthlyRentOverride`).
 * `estimateHomeSizingFromBudget`/`estimateMonthlyRentFromPrice` below hold
 * the same auto-sizing arithmetic `buildLayerOneComparison` always used,
 * exported standalone so RentVsBuy.tsx can preview the auto-computed
 * figure live — one formula, not two copies that could drift apart.
 *
 * Phase 9.4 (user feedback, looking at the Phase 9.3 form and chart:
 * "the annual appreciation & returns on surplus are the main levers for
 * simulating scenarios... in the graph, instead of bars... line charts
 * would be better... showing the year on year change, as well as the
 * possible cutovers"): `buildAnnualNetWorthTrajectory` below re-runs
 * `compare()` a second time for an already-built `LayerOneResult`, with
 * one horizon per year instead of the four canonical buckets, purely so
 * RentVsBuy.tsx can plot a real year-by-year line and find every year the
 * two scenarios' net worth actually crosses — not just report the nearest
 * of 5/10/15/25. `buildLayerOneComparison` itself is unchanged: its four
 * canonical horizons still drive the results table, the hurdle-rate
 * solver, the flagship Comparator's own table, Monte Carlo and CSV
 * export, none of which asked for finer granularity.
 */
import {
  getCostInflationIndexRules,
  getIncomeTaxRules,
  getStampDutyRules,
  stampDutyAndRegistrationCost,
} from '@fincalc/data';
import {
  compare,
  ownedPropertyPosition,
  principalForEmi,
  rentalExpensePosition,
  solveGrossSalaryForNetIncome,
  solveHurdleRate,
  type AgeBand,
  type CompareOptions,
  type ComparisonResult,
  type HouseholdTaxConfig,
  type MarketContext,
  type Scenario,
  type TaxRegime,
} from '@fincalc/engine';

import { buildMarketContext, type AssumptionSeries } from './market-context';

export const SUPPORTED_CITIES = [{ id: 'hyderabad', label: 'Hyderabad, Telangana' }] as const;
export type CityId = (typeof SUPPORTED_CITIES)[number]['id'];

export const HORIZON_OPTIONS = [5, 10, 15, 25] as const;
export type HorizonYears = (typeof HORIZON_OPTIONS)[number];

export interface LayerOneInputs {
  city: CityId;
  /** Monthly take-home (post-tax) household income, in rupees. */
  monthlyHouseholdIncomeNet: number;
  /** Monthly budget for housing — the equal-outflow target both scenarios are compared on. */
  monthlyHousingBudget: number;
  horizonYears: HorizonYears;

  // ---- Phase 9.2: every lever below is optional — omitted means "use the matching DEFAULT_* constant". ----
  /** Home loan interest rate, annual, as a percentage (8.5 means 8.5%). */
  homeLoanRatePercent?: number;
  /** Home loan tenure, in years. */
  homeLoanTenureYears?: number;
  /** Down payment as a percentage of the property price (20 means 20% down, 80% loan-to-value). */
  downPaymentPercent?: number;
  /** Long-run residential property appreciation, annual, as a percentage. */
  propertyAppreciationPercent?: number;
  /** The shared reinvestment/index-fund return both scenarios' surplus compounds at, annual, as a percentage. */
  reinvestmentRatePercent?: number;
  /** Assumed gross rental yield for a home equivalent to the one the Buy scenario buys — sizes the Rent scenario's rent unless `monthlyRentOverride` is supplied. */
  rentalYieldPercent?: number;
  /** Society maintenance + upkeep, as a percentage of the monthly housing budget reserved before sizing the EMI. */
  maintenancePercentOfBudget?: number;
  /** Municipal property tax, annualised, as a percentage of the annual housing budget. */
  propertyTaxPercentOfAnnualBudget?: number;
  /** Refundable security deposit on the rented home, expressed as a number of months' rent. */
  securityDepositMonths?: number;
  /** Household's income-tax regime — a household files one return, so this applies to both scenarios equally. */
  householdRegime?: TaxRegime;
  /** Household's age band, for slab/rebate purposes. */
  householdAge?: AgeBand;

  // ---- Phase 9.3: direct overrides for the two headline numbers that were still auto-derived. ----
  /** Base price of the home to buy, excluding stamp duty and registration. Overrides the budget-derived auto-sizing (see `estimateHomeSizingFromBudget`) when supplied. */
  homePriceOverride?: number;
  /** Assumed monthly rent for an equivalent home in the Rent scenario. Overrides the yield-derived auto-sizing (see `estimateMonthlyRentFromPrice`) when supplied. */
  monthlyRentOverride?: number;
}

// ---- Documented default assumptions (brief principle 8: err conservative; principle 5: every one inspectable and, since Phase 9.2, directly editable) ----

const PROPERTY_APPRECIATION_SERIES = 'property.appreciation';
/** Conservative long-run residential appreciation default — matches the rate used throughout Phase 4's own test scenarios. */
export const DEFAULT_PROPERTY_APPRECIATION_PERCENT = 6.0;

const SWEEP_SERIES = 'default.index_fund';
/** The single shared reinvestment rate for both scenarios' surplus — see the module doc comment on why this must never differ between scenarios. */
export const DEFAULT_REINVESTMENT_RATE_PERCENT = 11.0;

/** Typical current home-loan rate — an editable assumption, not a cited tax/stamp-duty figure. */
export const DEFAULT_HOME_LOAN_RATE_PERCENT = 8.5;
/** 20-year tenure: the common default a household takes regardless of which horizon they're evaluating the decision at. */
export const DEFAULT_HOME_LOAN_TENURE_YEARS = 20;
/** A conventional Indian home-loan down payment (80% loan-to-value). */
export const DEFAULT_DOWN_PAYMENT_PERCENT = 20;
/** Society maintenance + upkeep, as a fraction of the monthly housing budget reserved before sizing the EMI. */
export const DEFAULT_MAINTENANCE_PERCENT_OF_BUDGET = 2.0;
/** Municipal property tax, annualised, as a fraction of the *annual* housing budget. */
export const DEFAULT_PROPERTY_TAX_PERCENT_OF_ANNUAL_BUDGET = 1.0;
/** Assumed gross residential rental yield for a home equivalent to what the Buy scenario buys — a common Indian-metro ballpark, not a cited figure (see DEFAULT_HOME_LOAN_RATE_PERCENT's caveat). Sizes the Rent scenario's rent, not a tax/stamp-duty fact. */
export const DEFAULT_RENTAL_YIELD_PERCENT = 3.0;
export const DEFAULT_SECURITY_DEPOSIT_MONTHS = 3;

const HORIZONS_MONTHS = [60, 120, 180, 300] as const;

/** Household defaults, per the project's own established convention (decisions-and-workflow.md): the new regime is where the sharp edges live, and a 35-40-year-old household (the brief's own founding persona) is squarely working-age. */
export const DEFAULT_HOUSEHOLD_REGIME: TaxRegime = 'new';
export const DEFAULT_HOUSEHOLD_AGE: AgeBand = 'under60';

/**
 * Phase 9.3: the Buy scenario's home-price auto-sizing, pulled out of
 * `buildLayerOneComparison` so it can be reused as a live preview (the
 * "Base flat price" form field shows this value until the user overrides
 * it) without duplicating the arithmetic. Sizes a home whose EMI (after
 * reserving `maintenancePercentOfBudget` of the stated budget) exactly
 * matches what's left of `monthlyHousingBudget`.
 */
export function estimateHomeSizingFromBudget(params: {
  monthlyHousingBudget: number;
  homeLoanRatePercent?: number;
  homeLoanTenureYears?: number;
  downPaymentPercent?: number;
  maintenancePercentOfBudget?: number;
}): { propertyPrice: number; loanPrincipal: number } {
  const homeLoanRatePercent = params.homeLoanRatePercent ?? DEFAULT_HOME_LOAN_RATE_PERCENT;
  const homeLoanTenureYears = params.homeLoanTenureYears ?? DEFAULT_HOME_LOAN_TENURE_YEARS;
  const downPaymentPercent = params.downPaymentPercent ?? DEFAULT_DOWN_PAYMENT_PERCENT;
  const maintenancePercentOfBudget = params.maintenancePercentOfBudget ?? DEFAULT_MAINTENANCE_PERCENT_OF_BUDGET;

  const homeLoanRate = homeLoanRatePercent / 100;
  const homeLoanTenureMonths = homeLoanTenureYears * 12;
  const loanToValue = 1 - downPaymentPercent / 100;
  const maintenanceShareOfBudget = maintenancePercentOfBudget / 100;

  const targetEmi = params.monthlyHousingBudget * (1 - maintenanceShareOfBudget);
  const loanPrincipal = principalForEmi(targetEmi, homeLoanRate, homeLoanTenureMonths);
  const propertyPrice = loanPrincipal / loanToValue;
  return { propertyPrice, loanPrincipal };
}

/**
 * Phase 9.3: the Rent scenario's rent auto-sizing, pulled out the same way
 * — the "Assumed monthly rent" form field shows this value (computed off
 * whichever price is currently in effect, overridden or auto-sized) until
 * the user overrides it directly.
 */
export function estimateMonthlyRentFromPrice(propertyPrice: number, rentalYieldPercent: number = DEFAULT_RENTAL_YIELD_PERCENT): number {
  return Math.round((propertyPrice * (rentalYieldPercent / 100)) / 12);
}

function currentFy(date: Date = new Date()): string {
  const year = date.getUTCFullYear();
  const month = date.getUTCMonth() + 1; // 1-12
  const startYear = month >= 4 ? year : year - 1;
  return `${startYear}-${String((startYear + 1) % 100).padStart(2, '0')}`;
}

export interface LayerOneResult {
  result: ComparisonResult;
  scenarios: readonly [buy: Scenario, rent: Scenario];
  ctx: MarketContext;
  household: HouseholdTaxConfig;
  startFy: string;
  horizonsMonths: readonly number[];
  selectedHorizonMonths: number;
  /** What the Buy scenario's home actually costs and how it was financed — shown in the assumptions strip. */
  buy: {
    propertyPrice: number;
    loanPrincipal: number;
    entryCosts: number;
    loanRatePercent: number;
    tenureYears: number;
    downPaymentPercent: number;
  };
  /** The market rent assumed for an equivalent home in the Rent scenario. */
  rent: { assumedMonthlyRent: number; securityDeposit: number; rentalYieldPercent: number; securityDepositMonths: number };
  assumptions: readonly AssumptionSeries[];
}

export function buildLayerOneComparison(inputs: LayerOneInputs): LayerOneResult {
  if (inputs.monthlyHouseholdIncomeNet <= 0) throw new RangeError('Household income must be positive.');
  if (inputs.monthlyHousingBudget <= 0) throw new RangeError('Housing budget must be positive.');

  const homeLoanRatePercent = inputs.homeLoanRatePercent ?? DEFAULT_HOME_LOAN_RATE_PERCENT;
  const homeLoanTenureYears = inputs.homeLoanTenureYears ?? DEFAULT_HOME_LOAN_TENURE_YEARS;
  const downPaymentPercent = inputs.downPaymentPercent ?? DEFAULT_DOWN_PAYMENT_PERCENT;
  const propertyAppreciationPercent = inputs.propertyAppreciationPercent ?? DEFAULT_PROPERTY_APPRECIATION_PERCENT;
  const reinvestmentRatePercent = inputs.reinvestmentRatePercent ?? DEFAULT_REINVESTMENT_RATE_PERCENT;
  const rentalYieldPercent = inputs.rentalYieldPercent ?? DEFAULT_RENTAL_YIELD_PERCENT;
  const maintenancePercentOfBudget = inputs.maintenancePercentOfBudget ?? DEFAULT_MAINTENANCE_PERCENT_OF_BUDGET;
  const propertyTaxPercentOfAnnualBudget = inputs.propertyTaxPercentOfAnnualBudget ?? DEFAULT_PROPERTY_TAX_PERCENT_OF_ANNUAL_BUDGET;
  const securityDepositMonths = inputs.securityDepositMonths ?? DEFAULT_SECURITY_DEPOSIT_MONTHS;
  const householdRegime = inputs.householdRegime ?? DEFAULT_HOUSEHOLD_REGIME;
  const householdAge = inputs.householdAge ?? DEFAULT_HOUSEHOLD_AGE;

  if (downPaymentPercent < 0 || downPaymentPercent >= 100) {
    throw new RangeError('Down payment must be at least 0% and less than 100%.');
  }
  if (homeLoanTenureYears <= 0) throw new RangeError('Home loan tenure must be positive.');
  if (inputs.homePriceOverride !== undefined && inputs.homePriceOverride <= 0) {
    throw new RangeError('Home price must be positive.');
  }
  if (inputs.monthlyRentOverride !== undefined && inputs.monthlyRentOverride <= 0) {
    throw new RangeError('Monthly rent must be positive.');
  }

  const homeLoanRate = homeLoanRatePercent / 100;
  const homeLoanTenureMonths = homeLoanTenureYears * 12;
  const loanToValue = 1 - downPaymentPercent / 100;
  const propertyAppreciationRate = propertyAppreciationPercent / 100;
  const sweepRate = reinvestmentRatePercent / 100;
  const maintenanceShareOfBudget = maintenancePercentOfBudget / 100;
  const propertyTaxShareOfAnnualBudget = propertyTaxPercentOfAnnualBudget / 100;

  const startFy = currentFy();
  const incomeTaxRules = getIncomeTaxRules(startFy);
  const cii = getCostInflationIndexRules();
  const stampDutyRules = getStampDutyRules();

  const hyderabadRates = stampDutyRules.states.TG?.byLocalBody.municipal_corporation;
  if (!hyderabadRates) throw new Error('buildLayerOneComparison: Telangana municipal_corporation stamp-duty rates are not shipped.');

  // --- Size the Buy scenario: a direct price override (Phase 9.3) takes precedence over the budget-derived auto-sizing ---
  let propertyPrice: number;
  let loanPrincipal: number;
  if (inputs.homePriceOverride !== undefined) {
    propertyPrice = inputs.homePriceOverride;
    loanPrincipal = propertyPrice * loanToValue;
  } else {
    ({ propertyPrice, loanPrincipal } = estimateHomeSizingFromBudget({
      monthlyHousingBudget: inputs.monthlyHousingBudget,
      homeLoanRatePercent,
      homeLoanTenureYears,
      downPaymentPercent,
      maintenancePercentOfBudget,
    }));
  }
  const entryCosts = stampDutyAndRegistrationCost(propertyPrice, hyderabadRates);

  const buyScenario: Scenario = {
    id: 'buy',
    name: 'Buy',
    positions: [
      ownedPropertyPosition('buy:home', {
        purchasePrice: propertyPrice,
        entryCosts,
        loan: { principal: loanPrincipal, annualRate: () => homeLoanRate, tenureMonths: homeLoanTenureMonths },
        appreciationSeries: PROPERTY_APPRECIATION_SERIES,
        maintenancePerMonth: () => Math.round(inputs.monthlyHousingBudget * maintenanceShareOfBudget),
        annualPropertyTax: Math.round(inputs.monthlyHousingBudget * 12 * propertyTaxShareOfAnnualBudget),
        liquidityTier: 2,
      }),
    ],
    exitConfigs: [{ positionId: 'buy:home', capitalGainsTreatment: 'property', costOfAcquisition: propertyPrice + entryCosts }],
    growthAssumptions: [{ positionId: 'buy:home', seriesId: PROPERTY_APPRECIATION_SERIES, label: 'Buy: property appreciation' }],
    sweepGrowthSeries: SWEEP_SERIES,
    sweepExitConfig: { capitalGainsTreatment: 'equity' },
  };

  // --- Rent an equivalent home; a direct rent override (Phase 9.3) takes precedence over the yield-derived auto-sizing ---
  const assumedMonthlyRent = inputs.monthlyRentOverride ?? estimateMonthlyRentFromPrice(propertyPrice, rentalYieldPercent);
  const securityDeposit = assumedMonthlyRent * securityDepositMonths;

  const rentScenario: Scenario = {
    id: 'rent',
    name: 'Rent & invest the difference',
    positions: [rentalExpensePosition('rent:home', { monthlyRent: () => assumedMonthlyRent, securityDeposit })],
    exitConfigs: [{ positionId: 'rent:home', capitalGainsTreatment: 'none' }],
    sweepGrowthSeries: SWEEP_SERIES,
    sweepExitConfig: { capitalGainsTreatment: 'equity' },
  };

  const assumptions: AssumptionSeries[] = [
    { id: PROPERTY_APPRECIATION_SERIES, rate: propertyAppreciationRate, label: 'Property appreciation' },
    { id: SWEEP_SERIES, rate: sweepRate, label: 'Reinvestment instrument (broad index fund) — shared by both scenarios' },
  ];
  const ctx = buildMarketContext(assumptions);

  const grossSalaryAnnual = solveGrossSalaryForNetIncome(
    inputs.monthlyHouseholdIncomeNet * 12,
    { regime: householdRegime, age: householdAge },
    incomeTaxRules,
  );
  const household: HouseholdTaxConfig = {
    regime: householdRegime,
    age: householdAge,
    grossSalaryAnnual: () => grossSalaryAnnual,
  };

  const compareOptions: CompareOptions = {
    scenarios: [buyScenario, rentScenario],
    ctx,
    horizonsMonths: [...HORIZONS_MONTHS],
    startFy,
    household,
    cii,
  };
  const result = compare(compareOptions);

  const selectedHorizonMonths = inputs.horizonYears * 12;

  return {
    result,
    scenarios: [buyScenario, rentScenario],
    ctx,
    household,
    startFy,
    horizonsMonths: HORIZONS_MONTHS,
    selectedHorizonMonths,
    buy: {
      propertyPrice,
      loanPrincipal,
      entryCosts,
      loanRatePercent: homeLoanRatePercent,
      tenureYears: homeLoanTenureYears,
      downPaymentPercent,
    },
    rent: { assumedMonthlyRent, securityDeposit, rentalYieldPercent, securityDepositMonths },
    assumptions,
  };
}

/**
 * Phase 9.4: a year-by-year net worth trajectory for both scenarios in an
 * already-built `LayerOneResult` — see the module doc comment. Reuses the
 * exact `scenarios`/`ctx`/`startFy`/`household` that comparison already
 * built (never a second, potentially-drifting reconstruction of the
 * Buy/Rent scenarios themselves) and asks `compare()` for one horizon per
 * year instead of the four canonical buckets. `maxYears` defaults to the
 * longest of those four buckets (25, today), so the trajectory always
 * covers the same span the results table's last row does.
 */
export interface AnnualNetWorthPoint {
  year: number;
  buyNetWorth: number;
  rentNetWorth: number;
}

export function buildAnnualNetWorthTrajectory(layerOne: LayerOneResult, maxYears?: number): AnnualNetWorthPoint[] {
  const years = maxYears ?? Math.max(...layerOne.horizonsMonths) / 12;
  const horizonsMonths = Array.from({ length: years }, (_, i) => (i + 1) * 12);
  const result = compare({
    scenarios: [...layerOne.scenarios],
    ctx: layerOne.ctx,
    horizonsMonths,
    startFy: layerOne.startFy,
    household: layerOne.household,
    cii: getCostInflationIndexRules(),
  });
  const [buy, rent] = result.scenarios;
  return horizonsMonths.map((months, i) => ({
    year: months / 12,
    buyNetWorth: buy!.perHorizon[i]!.terminalNetWorth,
    rentNetWorth: rent!.perHorizon[i]!.terminalNetWorth,
  }));
}

export interface HurdleSentence {
  /** Which scenario is behind at the selected horizon and needs the higher rate. */
  laggingScenarioName: string;
  leadingScenarioName: string;
  /** The rate the lagging scenario's own growth assumption would need to compound at to match the leader — null if solveHurdleRate couldn't bracket a solution in a plausible range. */
  requiredRate: number | null;
  assumedRate: number;
}

/** The brief's headline output (principle 4): what return does the scenario behind need, to catch the one ahead, at the horizon the user actually asked about. */
export function computeHurdleSentence(layerOne: LayerOneResult): HurdleSentence {
  const horizonIndex = layerOne.horizonsMonths.indexOf(layerOne.selectedHorizonMonths);
  const idx = horizonIndex === -1 ? layerOne.horizonsMonths.length - 1 : horizonIndex;
  const horizonMonths = layerOne.horizonsMonths[idx]!;

  const [buyComparison, rentComparison] = layerOne.result.scenarios;
  const buyNetWorth = buyComparison!.perHorizon[idx]!.terminalNetWorth;
  const rentNetWorth = rentComparison!.perHorizon[idx]!.terminalNetWorth;

  const buyLeads = buyNetWorth >= rentNetWorth;
  const [buyScenario, rentScenario] = layerOne.scenarios;
  const laggingScenario = buyLeads ? rentScenario : buyScenario;
  const leadingScenarioName = buyLeads ? 'Buying' : 'Renting & investing';
  const laggingScenarioName = buyLeads ? 'Renting & investing' : 'Buying';
  const targetTerminalNetWorth = buyLeads ? buyNetWorth : rentNetWorth;
  const seriesToSolve = buyLeads ? SWEEP_SERIES : PROPERTY_APPRECIATION_SERIES;
  // Phase 9.2: both rates are now user-overridable, so the assumed rate shown must be read back
  // off this comparison's own resolved assumptions rather than a fixed module constant.
  const assumedRate = layerOne.assumptions.find((a) => a.id === seriesToSolve)?.rate ?? 0;

  const frozenTargetByMonth = layerOne.result.scenarios[0]!.equalisedMonthlyOutflow;

  try {
    const requiredRate = solveHurdleRate(
      laggingScenario,
      seriesToSolve,
      layerOne.ctx,
      frozenTargetByMonth,
      horizonMonths,
      targetTerminalNetWorth,
      layerOne.startFy,
      layerOne.household,
      getCostInflationIndexRules(),
    );
    return { laggingScenarioName, leadingScenarioName, requiredRate, assumedRate };
  } catch {
    return { laggingScenarioName, leadingScenarioName, requiredRate: null, assumedRate };
  }
}
