/**
 * Phase 8 (brief §4 "Sharing and persistence"): "Every scenario encodes
 * into the URL (compressed) so it is bookmarkable and shareable with no
 * backend." The payload lives in a `?s=` query parameter that sits
 * *before* the hash route (`?s=...#/comparator`) — GitHub Pages serves the
 * same static `index.html` regardless of query string, and this keeps the
 * URL's route and its scenario state as two independent, independently
 * parseable parts (see router.ts's own module doc for why routing itself
 * stays a plain hash rather than growing query-param awareness).
 *
 * Encoding: JSON.stringify -> UTF-8 bytes -> base64url. That is genuinely
 * more compact than writing every field name out in the query string (the
 * literal reading of "compressed" the brief asks for), and — more
 * importantly than the byte count — it is forward-compatible:
 * decodeScenarioState validates and narrows each field independently and
 * returns only the ones that parsed, so a link generated by an older
 * build (fewer fields) or a newer one (more fields, once Layer 2/3 land)
 * both still decode to *something* usable rather than throwing or
 * silently trusting a malformed value. A real compression pass (LZ-string
 * or similar) can replace the base64 step later without changing this
 * module's exported shape.
 *
 * Every function here that needs `window` takes the string it needs
 * (`search`, `currentUrl`) as a parameter with a `window`-reading wrapper
 * one layer up — so the actual parsing/encoding logic is plain,
 * dependency-free TypeScript that runs (and is tested) under Node, not
 * just in a browser.
 */
import { HORIZON_OPTIONS, SUPPORTED_CITIES, type CityId, type HorizonYears, type LayerOneInputs } from './scenario-builder';

const PARAM = 's';

function toBase64Url(bytes: Uint8Array): string {
  let binary = '';
  for (const b of bytes) binary += String.fromCharCode(b);
  return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

function fromBase64Url(encoded: string): Uint8Array {
  const normalized = encoded.replace(/-/g, '+').replace(/_/g, '/');
  const padded = normalized + '='.repeat((4 - (normalized.length % 4)) % 4);
  const binary = atob(padded);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

/** Encodes the exact inputs a Layer-1 comparison was built from into a single opaque, URL-safe token. */
export function encodeScenarioState(inputs: LayerOneInputs): string {
  const json = JSON.stringify(inputs);
  return toBase64Url(new TextEncoder().encode(json));
}

/**
 * Decodes a token produced by encodeScenarioState back into (validated)
 * Layer-1 inputs. Never throws and never trusts a field blindly — a
 * pasted link is untrusted input exactly like a form field, so every
 * field is narrowed against the same bounds the form itself enforces
 * (a known city, a real HorizonYears option, a positive finite amount)
 * before being accepted. Fields that fail validation are simply omitted
 * from the result rather than rejecting the whole link, so the caller can
 * merge whatever did parse onto its own defaults.
 */
export function decodeScenarioState(encoded: string): Partial<LayerOneInputs> | null {
  let parsed: unknown;
  try {
    const json = new TextDecoder().decode(fromBase64Url(encoded));
    parsed = JSON.parse(json);
  } catch {
    return null;
  }
  if (typeof parsed !== 'object' || parsed === null) return null;
  const candidate = parsed as Record<string, unknown>;

  const out: Partial<LayerOneInputs> = {};

  if (typeof candidate.city === 'string' && SUPPORTED_CITIES.some((c) => c.id === candidate.city)) {
    out.city = candidate.city as CityId;
  }
  if (
    typeof candidate.monthlyHouseholdIncomeNet === 'number' &&
    Number.isFinite(candidate.monthlyHouseholdIncomeNet) &&
    candidate.monthlyHouseholdIncomeNet > 0
  ) {
    out.monthlyHouseholdIncomeNet = candidate.monthlyHouseholdIncomeNet;
  }
  if (
    typeof candidate.monthlyHousingBudget === 'number' &&
    Number.isFinite(candidate.monthlyHousingBudget) &&
    candidate.monthlyHousingBudget > 0
  ) {
    out.monthlyHousingBudget = candidate.monthlyHousingBudget;
  }
  if (
    typeof candidate.horizonYears === 'number' &&
    (HORIZON_OPTIONS as readonly number[]).includes(candidate.horizonYears)
  ) {
    out.horizonYears = candidate.horizonYears as HorizonYears;
  }

  return out;
}

/** Reads and decodes the `s` param out of a URL's search string (e.g. `location.search`). Pure — takes the string rather than reading `window` itself, so it's testable without a DOM. */
export function readScenarioStateFromSearch(search: string): Partial<LayerOneInputs> | null {
  const params = new URLSearchParams(search);
  const encoded = params.get(PARAM);
  if (!encoded) return null;
  return decodeScenarioState(encoded);
}

/** Browser convenience wrapper: reads the current page's `?s=` param, or null outside a browser (or when absent/invalid). */
export function readScenarioStateFromUrl(): Partial<LayerOneInputs> | null {
  if (typeof window === 'undefined') return null;
  return readScenarioStateFromSearch(window.location.search);
}

/** Builds a full shareable URL (the given base URL's origin/path/hash, with `?s=` set to the encoded inputs) without touching `window` itself. */
export function buildShareUrl(inputs: LayerOneInputs, currentUrl: string): string {
  const url = new URL(currentUrl);
  url.searchParams.set(PARAM, encodeScenarioState(inputs));
  return url.toString();
}

/**
 * Writes the encoded inputs into the current URL's `?s=` param via
 * `history.replaceState` — no navigation, no new history entry, no
 * `hashchange` fired — so the address bar always reflects what's on
 * screen and is itself a valid, shareable, bookmarkable link even if the
 * visitor never touches the explicit "copy link" affordance.
 */
export function syncScenarioStateToUrl(inputs: LayerOneInputs): void {
  if (typeof window === 'undefined') return;
  const next = buildShareUrl(inputs, window.location.href);
  if (next !== window.location.href) window.history.replaceState(null, '', next);
}
